import Head from "next/head";
import Login from "../components/Login";
import { useMoralis } from "react-moralis";

export default function Home() {
  const isAuth = false;

  if (!isAuth) return <Login />;

  return (
    <div className="">
      <Head>
        <title>ChatApp Web-3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
